# Basic Python

## 1. Split this string

In [1]:
s = "Hi there Sam!"
s.split()


['Hi', 'there', 'Sam!']

: 

## 2. Use .format() to print the following string. 

### Output should be: The diameter of Earth is 12742 kilometers.

In [ ]:
planet = "Earth"
diameter = 12742


: 

In [7]:
planet = "Earth"
diameter = 12742
print('The diameter of {} is {} kilometers.' .format(planet, diameter))


The diameter of Earth is 12742 kilometers.


## 3. In this nest dictionary grab the word "hello"

In [ ]:
d = {'k1': [1, 2, 3, {'tricky': ['oh', 'man',
                                 'inception', {'target': [1, 2, 3, 'hello']}]}]}


: 

In [3]:
d = {
    'k1': [1, 2, 3, {
        'tricky': ['oh', 'man', 'inception', {
            'target': [1, 2, 3, 'hello']
        }]
    }]
}


# Numpy

In [ ]:
import numpy as np


: 

## 4.1 Create an array of 10 zeros? 
## 4.2 Create an array of 10 fives?

In [10]:
import numpy as np
array = np.zeros(10)
print("An array of 10 zeros:")
print(array)
array = np.ones(10)
print("An array of 10 ones:")
print(array)


An array of 10 zeros:
[0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
An array of 10 ones:
[1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]


In [12]:
array = np.ones(10)*5
print("An array of 10 fives:")
print(array)


An array of 10 fives:
[5. 5. 5. 5. 5. 5. 5. 5. 5. 5.]


## 5. Create an array of all the even integers from 20 to 35

In [8]:
import numpy as np
array = np.arange(20, 35, 2)
print("Array of all the even integers from 30 to 70")
print(array)


Array of all the even integers from 30 to 70
[20 22 24 26 28 30 32 34]


## 6. Create a 3x3 matrix with values ranging from 0 to 8

In [11]:
import numpy as np
x = np.arange(2, 11).reshape(3, 3)
print(x)


[[ 2  3  4]
 [ 5  6  7]
 [ 8  9 10]]


## 7. Concatinate a and b 
## a = np.array([1, 2, 3]), b = np.array([4, 5, 6])

In [14]:
import numpy as np
a = np.array([1, 2, 3])
b = np.array([4, 5, 6])
print(np.concatenate((a, b)))


[1 2 3 4 5 6]


# Pandas

## 8.Create a dataframe with 3 rows and 2 columns. 

In [14]:
lists = [[1, 'aaa', 22],
         [2, 'bbb', 25],
         [3, 'ccc', 24]]

df = pd.DataFrame (lists)
print (df)

   0    1   2
0  1  aaa  22
1  2  bbb  25
2  3  ccc  24


: 

## 9. Generate the series of dates from 1st Jan, 2023 to 10th Feb, 2023

In [2]:
import pandas as pd
pd.date_range(start='1/1/2023', end='10/02/2023', freq='M')


DatetimeIndex(['2023-01-31', '2023-02-28', '2023-03-31', '2023-04-30',
               '2023-05-31', '2023-06-30', '2023-07-31', '2023-08-31',
               '2023-09-30'],
              dtype='datetime64[ns]', freq='M')

## 10. Create 2D list to DataFrame

lists = [[1, 'aaa', 22],
         [2, 'bbb', 25],
         [3, 'ccc', 24]]

In [1]:
lists = [[1, 'aaa', 22], [2, 'bbb', 25], [3, 'ccc', 24]]


In [12]:
lists = [[1, 'aaa', 22],
         [2, 'bbb', 25],
         [3, 'ccc', 24]]

df = pd.DataFrame (lists)
print (df)

   0    1   2
0  1  aaa  22
1  2  bbb  25
2  3  ccc  24
